stages:
 - test
 - deploy

test:
  stage: test
  tags:
    - whitehole
    - shell
  before_script:
    - conda create --yes --prefix .\environment python=%PYTHON_VERSION%
    - conda env update --prefix .\environment
  script: conda run --prefix .\environment --no-capture-output pytest --cov --ignore=environment
  after_script:
    - conda env remove --prefix .\environment
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.6", "3.7", "3.8", "3.9"]

pip:
  stage: deploy
  tags:
    - whitehole
    - shell
  only:
    refs:
      - master
  before_script:
    - conda create --yes --prefix .\environment
    - conda env update --prefix .\environment
    - $Env:PYMETAIO_COMMIT_COUNT = (git rev-list --count HEAD)
  script: conda run --prefix .\environment --no-capture-output python setup.py sdist bdist_wheel
  after_script:
    - New-Item -Path "C:\istar\server\pip\pymetaio" -ItemType Directory -Force
    - Copy-Item -Path ".\dist\*" -Destination "C:\istar\server\pip\pymetaio" -Recurse

conda:
  stage: deploy
  tags:
    - whitehole
    - shell
  only:
    refs:
      - master
  before_script:
    - $Env:PYMETAIO_COMMIT_COUNT = (git rev-list --count HEAD)
  script: conda build --channel conda-forge --output-folder .\conda-build .\conda
  after_script:
    - Copy-Item -Path ".\conda-build\noarch\*.tar.bz2" -Destination "C:\istar\server\conda\noarch" -Recurse
    - conda index C:\istar\server\conda
