stages:
 - test
 - deploy

test:win:
  stage: test
  tags:
    - whitehole
    - shell
  before_script:
    - call conda.bat create --yes --prefix .\environment python=%PYTHON_VERSION%
    - call conda.bat env update --prefix .\environment
    - call activate.bat .\environment
  script: pytest
  after_script:
    - call conda.bat env remove --prefix .\environment
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.6", "3.7", "3.8"]
        DUMMY: ["dummy"]

test:linux:
  stage: test
  tags:
    - tartarus
    - shell
  before_script:
    - conda create --yes --prefix ./environment python=$PYTHON_VERSION
    - conda env update --prefix ./environment
    - source activate ./environment
  script: pytest
  after_script:
    - conda env remove --prefix ./environment
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.6", "3.7", "3.8"]
        DUMMY: ["dummy"]
