stages:
 - test

test:
  stage: test
  tags:
    - whitehole
    - shell
  before_script:
    - conda create --yes --prefix .\environment python=%PYTHON_VERSION%
    - conda env update --prefix .\environment
  script: conda run --prefix .\environment --no-capture-output pytest
  after_script:
    - conda env remove --prefix .\environment
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.6", "3.7", "3.8"]
        DUMMY: ["dummy"]
