channels:
  - defaults
  - conda-forge
dependencies:
  - imageio>=2.9
  - numpy>=1.19
  - python>=3.6
  # test requirements
  - flake8>=3.8
  - flake8-builtins
  - flake8-comprehensions
  - flake8-import-order
  - flake8-mutable
  - flake8-polyfill
  - pytest>=6.1
  - pytest-cov
  - pytest-flake8
  # pip requirements
  - pip>=20.2
  - pip:
    - --editable .
