channels:
  - conda-forge
  - defaults
dependencies:
  - imageio>=2.8
  - numpy>=1.19
  - python>=3.6
  # test
  - flake8>=4.0
  - flake8-builtins
  - flake8-comprehensions
  - flake8-import-order
  - flake8-mutable
  - flake8-quotes
  - pep8-naming
  - pytest>=6.2
  - pytest-cov
  - pytest-flake8
  # pip
  - pip>=21.3
  - pip:
    - --editable .
