package:
  name: pymetaio
  version: "0.1.{{ environ.get('PYMETAIO_COMMIT_COUNT', 0) }}"

source:
  path: ../

build:
  noarch: python
  script: pip install .
  string: g{{ GIT_FULL_HASH[:7] }}

requirements:
  host:
    - imageio >=2.9
    - numpy >=1.19
    - pip
    - python >=3.6
  run:
    - {{ pin_compatible('imageio', min_pin='x.x', max_pin='') }}
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='') }}

test:
  imports:
    - pymetaio
