package:
  name: metaimageio
  version: '0.9.0'

source:
  path: ../

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  string: g{{ GIT_FULL_HASH[:7] }}

requirements:
  build:
    - pip
    - python
  run:
    - imageio >=2.9
    - numpy >=1.20
    - python

test:
  imports:
    - metaimageio
