package:
  name: pymetaio
  version: "0.1.{{ environ.get('PYMETAIO_COMMIT_COUNT', 0) }}"

source:
  path: ../

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  string: g{{ GIT_FULL_HASH[:7] }}

requirements:
  host:
    - python >=3.6
    - setuptools >=50.3
  run:
    - {{ pin_compatible('python', min_pin='x.x', max_pin='') }}
    - imageio >=2.9
    - numpy >=1.19
    - pip >=20.2

test:
  imports:
    - pymetaio
