name: CI

on: [push]

jobs:

  test:
    name: test (${{ matrix.os }}, python-${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          python -m pip install .[flake8,pytest]
          python -m pytest .
          python -m pytest --cov .
